using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using PGD.Jobs.SourceGenerator.Analyzer;
using PGD.Jobs.SourceGenerator.CodeGen;
using PGD.Jobs.SourceGenerator.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PGD.Jobs.SourceGenerator
{
    /// <summary>
    /// 为实现 IJobParallel 接口的 Job 生成调度器代码
    /// </summary>
    [Generator]
    public class PGDJobSourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            // 注册语法接收器，用于收集候选的 Job 类型
            context.RegisterForSyntaxNotifications(() => new JobSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            // 获取语法接收器
            if (context.SyntaxReceiver is not JobSyntaxReceiver receiver)
                return;

            // 遍历所有候选的 Job
            foreach (var candidateStruct in receiver.CandidateStructs)
            {
                var model = context.Compilation.GetSemanticModel(candidateStruct.SyntaxTree);
                var structSymbol = model.GetDeclaredSymbol(candidateStruct) as INamedTypeSymbol;

                if (structSymbol == null)
                    continue;

                // 验证是否实现了 IJobParallel 接口
                if (!ImplementsIJobParallel(structSymbol, context.Compilation))
                    continue;

                // 验证是否为 partial
                if (!candidateStruct.Modifiers.Any(m => m.ValueText == "partial"))
                {
                    // 报告诊断错误：必须是 partial struct
                    var diagnostic = Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "PGDJOB001",
                            "Job must be partial",
                            "Job '{0}' must be declared as 'partial struct' to enable code generation",
                            "PGD.Jobs",
                            DiagnosticSeverity.Error,
                            true),
                        candidateStruct.GetLocation(),
                        structSymbol.Name);
                    context.ReportDiagnostic(diagnostic);
                    continue;
                }

                // 分析 Job
                var jobInfo = JobAnalyzer.AnalyzeJob(structSymbol, candidateStruct, context.Compilation);
                if (jobInfo == null)
                {
                    // 报告诊断错误：缺少 Execute 方法
                    var diagnostic = Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "PGDJOB002",
                            "Job must have Execute method",
                            "Job '{0}' must have an Execute method to enable code generation",
                            "PGD.Jobs",
                            DiagnosticSeverity.Error,
                            true),
                        candidateStruct.GetLocation(),
                        structSymbol.Name);
                    context.ReportDiagnostic(diagnostic);
                    continue;
                }

                // 生成代码
                try
                {
                    var generatedCode = GenerateJobCode(jobInfo);
                    var fileName = $"{jobInfo.JobName}_Generated.g.cs";
                    context.AddSource(fileName, SourceText.From(generatedCode, Encoding.UTF8));
                }
                catch (System.Exception ex)
                {
                    // 报告代码生成错误
                    var diagnostic = Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "PGDJOB999",
                            "Code generation failed",
                            "Failed to generate code for Job '{0}': {1}",
                            "PGD.Jobs",
                            DiagnosticSeverity.Error,
                            true),
                        candidateStruct.GetLocation(),
                        structSymbol.Name,
                        ex.Message);
                    context.ReportDiagnostic(diagnostic);
                }
            }
        }

        private bool ImplementsIJobParallel(INamedTypeSymbol structSymbol, Compilation compilation)
        {
            var iJobParallelSymbol = compilation.GetTypeByMetadataName("PGD.Jobs.IJobParallel");
            if (iJobParallelSymbol == null)
                return false;

            return structSymbol.AllInterfaces.Contains(iJobParallelSymbol, SymbolEqualityComparer.Default);
        }

        private string GenerateJobCode(JobInfo jobInfo)
        {
            var builder = new CodeBuilder();

            // 添加文件头
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();

            // 添加 using 语句
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine("using Unity.Collections;");
            builder.AppendLine("using Unity.Jobs;");
            builder.AppendLine("using PGD;");
            builder.AppendLine("using PGD.Jobs;");
            builder.AppendLine();

            // 命名空间
            if (!string.IsNullOrEmpty(jobInfo.Namespace))
            {
                builder.AppendLine($"namespace {jobInfo.Namespace}");
                builder.OpenBrace();
            }

            // 生成占位符描述器（TODO: 实现完整版本）
            GeneratePlaceholderDescriptor(builder, jobInfo);
            builder.AppendLine();

            // 生成扩展方法（覆盖运行时反射版本）
            ExtensionMethodGenerator.Generate(builder, jobInfo);

            if (!string.IsNullOrEmpty(jobInfo.Namespace))
            {
                builder.CloseBrace();
            }

            return builder.ToString();
        }

        private void GeneratePlaceholderDescriptor(CodeBuilder builder, JobInfo jobInfo)
        {
            var descriptorName = $"{jobInfo.JobName}_Descriptor";
            
            builder.AppendXmlComment($"Placeholder descriptor for {jobInfo.JobName}");
            builder.AppendComment("TODO: Implement full descriptor with query, context, wrapper, etc.");
            builder.AppendLine($"file sealed class {descriptorName} : global::PGD.Jobs.IPGDParallelJobDescriptor<{jobInfo.JobName}>");
            builder.OpenBrace();

            // CreateContext
            builder.AppendLine("public object CreateContext(global::PGD.IECSWorld world, global::Unity.Collections.Allocator allocator, ref " + jobInfo.JobName + " job)");
            builder.OpenBrace();
            builder.AppendLine("return null;");
            builder.CloseBrace();
            builder.AppendLine();

            // Schedule
            builder.AppendLine("public global::Unity.Jobs.JobHandle Schedule(global::PGD.IECSWorld world, ref " + jobInfo.JobName + " job, object context, global::Unity.Jobs.JobHandle dependsOn)");
            builder.OpenBrace();
            builder.AppendLine("// Placeholder: falls back to reflection");
            builder.AppendLine("return global::PGD.Jobs.PGDJobReflectionRegistry.GetOrCreateDescriptor<" + jobInfo.JobName + ">().Schedule(world, ref job, context, dependsOn);");
            builder.CloseBrace();
            builder.AppendLine();

            // OnJobCompleted
            builder.AppendLine("public void OnJobCompleted(global::PGD.IECSWorld world, object context)");
            builder.OpenBrace();
            builder.CloseBrace();
            builder.AppendLine();

            // DisposeContext
            builder.AppendLine("public void DisposeContext(object context)");
            builder.OpenBrace();
            builder.CloseBrace();

            builder.CloseBrace();
        }
    }

    /// <summary>
    /// 语法接收器：收集所有 partial struct 候选
    /// </summary>
    internal class JobSyntaxReceiver : ISyntaxReceiver
    {
        public List<StructDeclarationSyntax> CandidateStructs { get; } = new List<StructDeclarationSyntax>();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            // 查找 partial struct 声明
            if (syntaxNode is StructDeclarationSyntax structDeclaration &&
                structDeclaration.Modifiers.Any(m => m.ValueText == "partial"))
            {
                CandidateStructs.Add(structDeclaration);
            }
        }
    }
}

