using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using PGD.Jobs.SourceGenerator.Analyzer;
using PGD.Jobs.SourceGenerator.CodeGen;
using PGD.Jobs.SourceGenerator.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PGD.Jobs.SourceGenerator
{
    /// <summary>
    /// 为实现 IJobParallel 接口的 Job 生成调度器代码
    /// </summary>
    [Generator]
    public class PGDJobSourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            // 注册语法接收器，用于收集候选的 Job 类型
            context.RegisterForSyntaxNotifications(() => new JobSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            // 获取语法接收器
            if (context.SyntaxReceiver is not JobSyntaxReceiver receiver)
                return;

            // 遍历所有候选的 Job
            foreach (var candidateStruct in receiver.CandidateStructs)
            {
                var model = context.Compilation.GetSemanticModel(candidateStruct.SyntaxTree);
                var structSymbol = model.GetDeclaredSymbol(candidateStruct) as INamedTypeSymbol;

                if (structSymbol == null)
                    continue;

                // 验证是否实现了 IJobParallel 接口
                if (!ImplementsIJobParallel(structSymbol, context.Compilation))
                    continue;

                // 验证是否为 partial
                if (!candidateStruct.Modifiers.Any(m => m.ValueText == "partial"))
                {
                    // 报告诊断错误：必须是 partial struct
                    var diagnostic = Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "PGDJOB001",
                            "Job must be partial",
                            "Job '{0}' must be declared as 'partial struct' to enable code generation",
                            "PGD.Jobs",
                            DiagnosticSeverity.Error,
                            true),
                        candidateStruct.GetLocation(),
                        structSymbol.Name);
                    context.ReportDiagnostic(diagnostic);
                    continue;
                }

                // 分析 Job
                var jobInfo = JobAnalyzer.AnalyzeJob(structSymbol, candidateStruct, context.Compilation);
                if (jobInfo == null)
                {
                    // 报告诊断错误：缺少 Execute 方法
                    var diagnostic = Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "PGDJOB002",
                            "Job must have Execute method",
                            "Job '{0}' must have an Execute method to enable code generation",
                            "PGD.Jobs",
                            DiagnosticSeverity.Error,
                            true),
                        candidateStruct.GetLocation(),
                        structSymbol.Name);
                    context.ReportDiagnostic(diagnostic);
                    continue;
                }

                // 生成代码
                try
                {
                    var generatedCode = GenerateJobCode(jobInfo);
                    var fileName = $"{jobInfo.JobName}_Generated.g.cs";
                    context.AddSource(fileName, SourceText.From(generatedCode, Encoding.UTF8));
                }
                catch (System.Exception ex)
                {
                    // 报告代码生成错误
                    var diagnostic = Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "PGDJOB999",
                            "Code generation failed",
                            "Failed to generate code for Job '{0}': {1}",
                            "PGD.Jobs",
                            DiagnosticSeverity.Error,
                            true),
                        candidateStruct.GetLocation(),
                        structSymbol.Name,
                        ex.Message);
                    context.ReportDiagnostic(diagnostic);
                }
            }
        }

        private bool ImplementsIJobParallel(INamedTypeSymbol structSymbol, Compilation compilation)
        {
            var iJobParallelSymbol = compilation.GetTypeByMetadataName("PGD.Jobs.IJobParallel");
            if (iJobParallelSymbol == null)
                return false;

            return structSymbol.AllInterfaces.Contains(iJobParallelSymbol, SymbolEqualityComparer.Default);
        }

        private string GenerateJobCode(JobInfo jobInfo)
        {
            var builder = new CodeBuilder();

            // 添加文件头
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("// This file is generated by PGD.Jobs.SourceGenerator");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();

            // 添加 using 语句
            builder.AppendLine("using Unity.Jobs;");
            builder.AppendLine("using UnityEngine;");
            builder.AppendLine("using PGD;");
            builder.AppendLine("using PGD.Jobs;");
            builder.AppendLine();

            // 命名空间
            if (!string.IsNullOrEmpty(jobInfo.Namespace))
            {
                builder.AppendLine($"namespace {jobInfo.Namespace}");
                builder.OpenBrace();
            }

            // 生成扩展方法类
            GenerateExtensionMethods(builder, jobInfo);

            if (!string.IsNullOrEmpty(jobInfo.Namespace))
            {
                builder.CloseBrace();
            }

            return builder.ToString();
        }

        private void GenerateExtensionMethods(CodeBuilder builder, JobInfo jobInfo)
        {
            // 生成一个静态类，包含该 Job 的扩展方法
            // 使用 file 关键字限制作用域，避免命名冲突
            builder.AppendXmlComment($"Generated extension methods for {jobInfo.JobName}");
            builder.AppendLine($"internal static class {jobInfo.JobName}Extensions");
            builder.OpenBrace();

            // ScheduleParallel() - DOTS 风格无参数版本
            builder.AppendXmlComment("Schedules the job for parallel execution (DOTS-style, no parameters).");
            builder.AppendXmlComment("This method is generated by Source Generator and overrides the default implementation.");
            builder.AppendLine($"public static void ScheduleParallel(this ref {jobInfo.JobName} job)");
            builder.OpenBrace();
            
            builder.AppendComment("TODO: Auto-generate query, data extraction, scheduling, and cleanup");
            builder.AppendComment("For now, log a message to verify Source Generator is working");
            builder.AppendLine($"global::UnityEngine.Debug.Log(\"[PGD.Jobs] {jobInfo.JobName}.ScheduleParallel() - Source Generator stub\");");
            
            builder.AppendComment("");
            builder.AppendComment("Example of what will be generated:");
            builder.AppendComment("1. var world = PGDJobSystemBase.CurrentWorld;");
            builder.AppendComment("2. var query = world.Query<Components...>();");
            builder.AppendComment("3. Extract data to NativeArray");
            builder.AppendComment("4. Create wrapper job");
            builder.AppendComment("5. Schedule with IJobParallelFor");
            builder.AppendComment("6. Register callbacks for data writeback and cleanup");
            
            builder.CloseBrace();
            builder.AppendLine();

            // ScheduleParallel(IQuery) - 带自定义查询
            builder.AppendXmlComment("Schedules the job for parallel execution with a custom query.");
            builder.AppendLine($"public static void ScheduleParallel(this ref {jobInfo.JobName} job, global::PGD.IQuery query)");
            builder.OpenBrace();
            
            builder.AppendLine($"global::UnityEngine.Debug.Log(\"[PGD.Jobs] {jobInfo.JobName}.ScheduleParallel(query) - Source Generator stub\");");
            builder.AppendComment("TODO: Use provided query instead of auto-generating one");
            
            builder.CloseBrace();

            builder.CloseBrace();
        }
    }

    /// <summary>
    /// 语法接收器：收集所有 partial struct 候选
    /// </summary>
    internal class JobSyntaxReceiver : ISyntaxReceiver
    {
        public List<StructDeclarationSyntax> CandidateStructs { get; } = new List<StructDeclarationSyntax>();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            // 查找 partial struct 声明
            if (syntaxNode is StructDeclarationSyntax structDeclaration &&
                structDeclaration.Modifiers.Any(m => m.ValueText == "partial"))
            {
                CandidateStructs.Add(structDeclaration);
            }
        }
    }
}

