using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using PGD.Jobs.SourceGenerator.Analyzer;
using PGD.Jobs.SourceGenerator.CodeGen;
using PGD.Jobs.SourceGenerator.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PGD.Jobs.SourceGenerator
{
    /// <summary>
    /// 为实现 IJobParallel 接口的 Job 生成调度器代码
    /// </summary>
    [Generator]
    public class PGDJobSourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            // 注册语法接收器，用于收集候选的 Job 类型
            context.RegisterForSyntaxNotifications(() => new JobSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            // 获取语法接收器
            if (context.SyntaxReceiver is not JobSyntaxReceiver receiver)
                return;

            // 遍历所有候选的 Job
            foreach (var candidateStruct in receiver.CandidateStructs)
            {
                var model = context.Compilation.GetSemanticModel(candidateStruct.SyntaxTree);
                var structSymbol = model.GetDeclaredSymbol(candidateStruct) as INamedTypeSymbol;

                if (structSymbol == null)
                    continue;

                // 验证是否实现了 IJobParallel 接口
                if (!ImplementsIJobParallel(structSymbol, context.Compilation))
                    continue;

                // 验证是否为 partial
                if (!candidateStruct.Modifiers.Any(m => m.ValueText == "partial"))
                {
                    // 报告诊断错误：必须是 partial struct
                    var diagnostic = Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "PGDJOB001",
                            "Job must be partial",
                            "Job '{0}' must be declared as 'partial struct' to enable code generation",
                            "PGD.Jobs",
                            DiagnosticSeverity.Error,
                            true),
                        candidateStruct.GetLocation(),
                        structSymbol.Name);
                    context.ReportDiagnostic(diagnostic);
                    continue;
                }

                // 分析 Job
                var jobInfo = JobAnalyzer.AnalyzeJob(structSymbol, candidateStruct, context.Compilation);
                if (jobInfo == null)
                {
                    // 报告诊断错误：缺少 Execute 方法
                    var diagnostic = Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "PGDJOB002",
                            "Job must have Execute method",
                            "Job '{0}' must have an Execute method to enable code generation",
                            "PGD.Jobs",
                            DiagnosticSeverity.Error,
                            true),
                        candidateStruct.GetLocation(),
                        structSymbol.Name);
                    context.ReportDiagnostic(diagnostic);
                    continue;
                }

                // 生成代码
                try
                {
                    var generatedCode = GenerateJobCode(jobInfo);
                    var fileName = $"{jobInfo.JobName}_Generated.g.cs";
                    context.AddSource(fileName, SourceText.From(generatedCode, Encoding.UTF8));
                }
                catch (System.Exception ex)
                {
                    // 报告代码生成错误
                    var diagnostic = Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "PGDJOB999",
                            "Code generation failed",
                            "Failed to generate code for Job '{0}': {1}",
                            "PGD.Jobs",
                            DiagnosticSeverity.Error,
                            true),
                        candidateStruct.GetLocation(),
                        structSymbol.Name,
                        ex.Message);
                    context.ReportDiagnostic(diagnostic);
                }
            }
        }

        private bool ImplementsIJobParallel(INamedTypeSymbol structSymbol, Compilation compilation)
        {
            var iJobParallelSymbol = compilation.GetTypeByMetadataName("PGD.Jobs.IJobParallel");
            if (iJobParallelSymbol == null)
                return false;

            return structSymbol.AllInterfaces.Contains(iJobParallelSymbol, SymbolEqualityComparer.Default);
        }

        private string GenerateJobCode(JobInfo jobInfo)
        {
            var builder = new CodeBuilder();

            // 添加文件头
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("// This file is generated by PGD.Jobs.SourceGenerator");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();

            // 添加 using 语句
            builder.AppendLine("using Unity.Jobs;");
            builder.AppendLine("using Unity.Collections;");
            builder.AppendLine("using UnityEngine;");
            builder.AppendLine("using PGD;");
            builder.AppendLine("using PGD.Jobs;");
            builder.AppendLine("using System.Linq;");
            builder.AppendLine();

            // 命名空间
            if (!string.IsNullOrEmpty(jobInfo.Namespace))
            {
                builder.AppendLine($"namespace {jobInfo.Namespace}");
                builder.OpenBrace();
            }

            // 生成包装 Job 结构体
            GenerateWrapperJob(builder, jobInfo);
            builder.AppendLine();

            // 生成 ExecuteGenerated 适配方法
            GenerateExecuteGeneratedMethod(builder, jobInfo);
            builder.AppendLine();

            // 生成扩展方法类
            GenerateExtensionMethods(builder, jobInfo);

            if (!string.IsNullOrEmpty(jobInfo.Namespace))
            {
                builder.CloseBrace();
            }

            return builder.ToString();
        }

        private void GenerateWrapperJob(CodeBuilder builder, JobInfo jobInfo)
        {
            var componentParameters = jobInfo.Parameters.Where(p => p.IsComponent).ToList();
            var fieldNames = BuildNativeArrayFieldNames(componentParameters);
            var hasEntityParameter = jobInfo.Parameters.Any(p => p.IsEntity);
            var hasEntityIndexParameter = jobInfo.Parameters.Any(p => p.IsEntityIndex);

            // 生成包装 Job 结构体
            builder.AppendXmlComment($"Wrapper job for {jobInfo.JobName} that implements IJobParallelFor");
            builder.AppendLine("[global::Unity.Burst.BurstCompile]");
            builder.AppendLine($"internal struct {jobInfo.JobName}_Wrapper : global::Unity.Jobs.IJobParallelFor");
            builder.OpenBrace();

            // 添加原始 Job 字段
            builder.AppendXmlComment("The original job to execute");
            builder.AppendLine($"public {jobInfo.JobName} innerJob;");
            builder.AppendLine();

            // 添加组件 NativeArray 字段
            if (componentParameters.Count > 0)
            {
                builder.AppendXmlComment("Component data arrays");
                foreach (var parameter in componentParameters)
                {
                    var fieldName = fieldNames[parameter];
                    if (parameter.IsReadOnly)
                    {
                        builder.AppendLine("[global::Unity.Collections.ReadOnly]");
                    }
                    builder.AppendLine($"public global::Unity.Collections.NativeArray<{parameter.TypeFullName}> {fieldName};");
                }
                builder.AppendLine();
            }

            // 添加实体数组字段（如果需要）
            if (hasEntityParameter)
            {
                builder.AppendXmlComment("Entity references array");
                builder.AppendLine("[global::Unity.Collections.ReadOnly]");
                builder.AppendLine("public global::Unity.Collections.NativeArray<global::PGD.IEntity> s_entityArray;");
                builder.AppendLine();
            }

            // 生成 Execute 方法
            builder.AppendXmlComment("Execute the job for a single entity index");
            builder.AppendLine("public void Execute(int index)");
            builder.OpenBrace();

            // 从 NativeArray 中提取参数
            foreach (var parameter in componentParameters)
            {
                var fieldName = fieldNames[parameter];
                var localVarName = parameter.Name;
                builder.AppendLine($"var {localVarName} = {fieldName}[index];");
            }

            if (hasEntityParameter)
            {
                var entityParam = jobInfo.Parameters.First(p => p.IsEntity);
                builder.AppendLine($"var {entityParam.Name} = s_entityArray[index];");
            }

            builder.AppendLine();

            // 调用原始 Execute 方法
            builder.AppendComment("Call the original Execute method");
            var executeArgs = BuildExecuteCallArguments(jobInfo);
            builder.AppendLine($"innerJob.ExecuteGenerated({executeArgs});");
            builder.AppendLine();

            // 写回可写参数
            var writableParameters = componentParameters.Where(p => p.RequiresWriteBack).ToList();
            if (writableParameters.Count > 0)
            {
                builder.AppendComment("Write back modified components");
                foreach (var parameter in writableParameters)
                {
                    var fieldName = fieldNames[parameter];
                    builder.AppendLine($"{fieldName}[index] = {parameter.Name};");
                }
            }

            builder.CloseBrace(); // Execute
            builder.CloseBrace(); // Wrapper struct
        }

        private void GenerateExecuteGeneratedMethod(CodeBuilder builder, JobInfo jobInfo)
        {
            // 生成适配方法
            builder.AppendXmlComment($"Generated adapter method for {jobInfo.JobName}.Execute");
            builder.AppendLine($"partial struct {jobInfo.JobName}");
            builder.OpenBrace();

            builder.AppendLine("[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            var methodSignature = BuildExecuteGeneratedSignature(jobInfo);
            builder.AppendLine($"internal void ExecuteGenerated({methodSignature})");
            builder.OpenBrace();

            var executeArgs = BuildExecuteCallArguments(jobInfo);
            builder.AppendLine($"Execute({executeArgs});");

            builder.CloseBrace(); // ExecuteGenerated
            builder.CloseBrace(); // partial struct
        }

        private string BuildExecuteGeneratedSignature(JobInfo jobInfo)
        {
            var parts = new List<string>();
            foreach (var parameter in jobInfo.Parameters)
            {
                var refModifier = parameter.RefKind switch
                {
                    RefKind.Ref => "ref ",
                    RefKind.In => "in ",
                    RefKind.Out => "out ",
                    _ => ""
                };
                parts.Add($"{refModifier}{parameter.TypeFullName} {parameter.Name}");
            }
            return string.Join(", ", parts);
        }

        private string BuildExecuteCallArguments(JobInfo jobInfo)
        {
            var parts = new List<string>();
            foreach (var parameter in jobInfo.Parameters)
            {
                var refModifier = parameter.RefKind switch
                {
                    RefKind.Ref => "ref ",
                    RefKind.In => "in ",
                    RefKind.Out => "out ",
                    _ => ""
                };

                if (parameter.IsEntityIndex)
                {
                    // 对于 entityIndex 参数，直接传递 index
                    parts.Add($"{refModifier}index");
                }
                else
                {
                    parts.Add($"{refModifier}{parameter.Name}");
                }
            }
            return string.Join(", ", parts);
        }

        private void GenerateJobScheduling(
            CodeBuilder builder, 
            JobInfo jobInfo, 
            Dictionary<ParameterInfo, string> fieldNames, 
            List<ParameterInfo> componentParameters)
        {
            var hasEntityParameter = jobInfo.Parameters.Any(p => p.IsEntity);
            var writableParameters = componentParameters.Where(p => p.RequiresWriteBack).ToList();

            builder.AppendComment("4. Create wrapper job");
            builder.AppendLine($"var wrapper = new {jobInfo.JobName}_Wrapper");
            builder.OpenBrace();
            builder.AppendLine("innerJob = job,");
            
            foreach (var parameter in componentParameters)
            {
                var fieldName = fieldNames[parameter];
                builder.AppendLine($"{fieldName} = {fieldName},");
            }

            if (hasEntityParameter)
            {
                builder.AppendLine("s_entityArray = s_entityArray,");
            }

            builder.CloseBrace(";");
            builder.AppendLine();

            builder.AppendComment("5. Schedule the job");
            builder.AppendLine("var dependency = global::PGD.Jobs.PGDJobSystemBase.CurrentDependency;");
            builder.AppendLine("var handle = wrapper.Schedule(entityCount, 64, dependency);");
            builder.AppendLine();

            builder.AppendComment("6. Register callbacks for data writeback and cleanup");
            builder.AppendLine("global::PGD.Jobs.PGDJobSystemBase.RegisterJob(");
            builder.Indent();
            builder.AppendLine("handle,");
            
            // onComplete 回调
            builder.AppendLine("onComplete: () =>");
            builder.OpenBrace();
            
            if (writableParameters.Count > 0)
            {
                builder.AppendComment("Write back modified components to entities");
                builder.AppendLine("int index = 0;");
                builder.AppendLine("foreach (var entity in query.Entities)");
                builder.OpenBrace();
                
                foreach (var parameter in writableParameters)
                {
                    var fieldName = fieldNames[parameter];
                    
                    // 如果检测到具体被修改的成员，只写回这些成员
                    if (parameter.ModifiedMembers.Count > 0)
                    {
                        builder.AppendComment($"Write back modified members of {parameter.TypeName}");
                        builder.AppendLine($"ref var {parameter.Name} = ref entity.GetComponent<{parameter.TypeFullName}>();");
                        foreach (var memberName in parameter.ModifiedMembers)
                        {
                            builder.AppendLine($"{parameter.Name}.{memberName} = {fieldName}[index].{memberName};");
                        }
                    }
                    // 否则写回整个组件（兜底方案）
                    else if (parameter.IsFullyModified)
                    {
                        builder.AppendComment($"Write back entire {parameter.TypeName} (full component modification detected)");
                        builder.AppendLine($"ref var {parameter.Name} = ref entity.GetComponent<{parameter.TypeFullName}>();");
                        builder.AppendLine($"{parameter.Name} = {fieldName}[index];");
                    }
                }
                
                builder.AppendLine("index++;");
                builder.CloseBrace();
            }
            else
            {
                builder.AppendComment("No writable components, nothing to write back");
            }
            
            builder.CloseBrace(",");
            
            // onDispose 回调
            builder.AppendLine("onDispose: () =>");
            builder.OpenBrace();
            builder.AppendComment("Dispose NativeArrays");
            
            foreach (var parameter in componentParameters)
            {
                var fieldName = fieldNames[parameter];
                builder.AppendLine($"if ({fieldName}.IsCreated) {fieldName}.Dispose();");
            }

            if (hasEntityParameter)
            {
                builder.AppendLine("if (s_entityArray.IsCreated) s_entityArray.Dispose();");
            }
            
            builder.CloseBrace(");");
            builder.Unindent();
        }

        private void GenerateExtensionMethods(CodeBuilder builder, JobInfo jobInfo)
        {
            // 生成一个静态类，包含该 Job 的扩展方法
            // 使用 file 关键字限制作用域，避免命名冲突
            builder.AppendXmlComment($"Generated extension methods for {jobInfo.JobName}");
            builder.AppendLine($"internal static class {jobInfo.JobName}Extensions");
            builder.OpenBrace();

            var componentParameters = jobInfo.Parameters.Where(p => p.IsComponent).ToList();
            var fieldNames = BuildNativeArrayFieldNames(componentParameters);
            var hasEntityParameter = jobInfo.Parameters.Any(p => p.IsEntity);

            if (componentParameters.Count > 0)
            {
                foreach (var parameter in componentParameters)
                {
                    var fieldName = fieldNames[parameter];
                    builder.AppendLine($"private static NativeArray<{parameter.TypeFullName}> {fieldName};");
                }
                builder.AppendLine();
            }

            if (hasEntityParameter)
            {
                builder.AppendLine("private static NativeArray<global::PGD.IEntity> s_entityArray;");
                builder.AppendLine();
            }

            // ScheduleParallel() - DOTS 风格无参数版本
            builder.AppendXmlComment("Schedules the job for parallel execution (DOTS-style, no parameters).");
            builder.AppendXmlComment("This method is generated by Source Generator and overrides the default implementation.");
            builder.AppendLine($"public static void ScheduleParallel(this ref {jobInfo.JobName} job)");
            builder.OpenBrace();
            builder.AppendLine("var world = global::PGD.Jobs.PGDJobSystemBase.CurrentWorld;");
            builder.AppendLine("if (world == null)");
            builder.OpenBrace();
            builder.AppendLine($"global::UnityEngine.Debug.LogError(\"[PGD.Jobs] {jobInfo.JobName}.ScheduleParallel() can only be called inside PGDJobSystemBase.OnUpdate().\");");
            builder.AppendLine("return;");
            builder.CloseBrace();
            builder.AppendLine();

            builder.AppendLine("var query = world.Query();");

            if (componentParameters.Count > 0)
            {
                builder.AppendLine("var requiredComponents = new global::PGD.IComponents();");
                var distinctComponentTypes = componentParameters
                    .Select(p => p.TypeFullName)
                    .Distinct()
                    .ToList();
                foreach (var componentType in distinctComponentTypes)
                {
                    builder.AppendLine($"requiredComponents.Add<{componentType}>();");
                }
                builder.AppendLine("query = query.WithAllComponents(requiredComponents);");
                builder.AppendLine();
            }

            // Apply WithAll filter
            GenerateWithAllFilter(builder, jobInfo);

            // Apply WithAny filter
            GenerateWithAnyFilter(builder, jobInfo);

            // Apply WithNone filter
            GenerateWithNoneFilter(builder, jobInfo);

            builder.AppendLine("var entityCount = query.EntityCount;");
            builder.AppendLine("if (entityCount == 0)");
            builder.OpenBrace();
            builder.AppendLine("return;");
            builder.CloseBrace();
            builder.AppendLine();

            foreach (var parameter in componentParameters)
            {
                var fieldName = fieldNames[parameter];
                builder.AppendLine($"if ({fieldName}.IsCreated)");
                builder.OpenBrace();
                builder.AppendLine($"{fieldName}.Dispose();");
                builder.CloseBrace();
                builder.AppendLine($"{fieldName} = new global::Unity.Collections.NativeArray<{parameter.TypeFullName}>(entityCount, global::Unity.Collections.Allocator.TempJob);");
            }

            if (hasEntityParameter)
            {
                builder.AppendLine("if (s_entityArray.IsCreated)");
                builder.OpenBrace();
                builder.AppendLine("s_entityArray.Dispose();");
                builder.CloseBrace();
                builder.AppendLine("s_entityArray = new global::Unity.Collections.NativeArray<global::PGD.IEntity>(entityCount, global::Unity.Collections.Allocator.TempJob);");
            }

            if (componentParameters.Count > 0 || hasEntityParameter)
            {
                builder.AppendLine();
                builder.AppendComment("Extract component data using foreach for better performance");
                builder.AppendLine("int index = 0;");
                builder.AppendLine("foreach (var entity in query.Entities)");
                builder.OpenBrace();
                
                if (hasEntityParameter)
                {
                    builder.AppendLine("s_entityArray[index] = entity;");
                }
                
                foreach (var parameter in componentParameters)
                {
                    var fieldName = fieldNames[parameter];
                    builder.AppendLine($"{fieldName}[index] = entity.GetComponent<{parameter.TypeFullName}>();");
                }
                
                builder.AppendLine("index++;");
                builder.CloseBrace();
                builder.AppendLine();
            }

            // 生成调度逻辑
            GenerateJobScheduling(builder, jobInfo, fieldNames, componentParameters);

            builder.CloseBrace();
            builder.AppendLine();

            // ScheduleParallel(IQuery) - 带自定义查询
            builder.AppendXmlComment("Schedules the job for parallel execution with a custom query.");
            builder.AppendLine($"public static void ScheduleParallel(this ref {jobInfo.JobName} job, global::PGD.IQuery query)");
            builder.OpenBrace();
            
            builder.AppendLine($"global::UnityEngine.Debug.Log(\"[PGD.Jobs] {jobInfo.JobName}.ScheduleParallel(query) - Source Generator stub\");");
            builder.AppendComment("TODO: Use provided query instead of auto-generating one");
            
            builder.CloseBrace();

            builder.CloseBrace();
        }

        private static Dictionary<ParameterInfo, string> BuildNativeArrayFieldNames(IReadOnlyList<ParameterInfo> parameters)
        {
            var result = new Dictionary<ParameterInfo, string>(parameters.Count);
            var usedNames = new HashSet<string>(StringComparer.Ordinal);
            foreach (var parameter in parameters)
            {
                result[parameter] = GetNativeArrayFieldName(parameter, usedNames);
            }
            return result;
        }

        private static string GetNativeArrayFieldName(ParameterInfo parameter, HashSet<string> usedNames)
        {
            var baseName = GetSanitizedIdentifier(parameter.Name);
            if (string.IsNullOrWhiteSpace(baseName))
            {
                baseName = parameter.TypeName;
            }

            var candidate = $"s_{baseName}Array";
            var index = 1;
            while (!usedNames.Add(candidate))
            {
                candidate = $"s_{baseName}{index}Array";
                index++;
            }

            return candidate;
        }

        private static string GetSanitizedIdentifier(string identifier)
        {
            if (string.IsNullOrEmpty(identifier))
                return identifier;

            return identifier[0] == '@'
                ? identifier.Substring(1)
                : identifier;
        }

        private static string BuildParameterSummary(JobInfo jobInfo)
        {
            if (jobInfo.Parameters.Count == 0)
                return "none";

            var parts = new List<string>(jobInfo.Parameters.Count);
            foreach (var parameter in jobInfo.Parameters)
            {
                var roles = new List<string>();
                if (parameter.IsEntity)
                {
                    roles.Add("entity");
                }
                else if (parameter.IsEntityIndex)
                {
                    roles.Add("index");
                }
                else
                {
                    roles.Add("component");
                    switch (parameter.RefKind)
                    {
                        case RefKind.Ref:
                            roles.Add("ref");
                            break;
                        case RefKind.In:
                            roles.Add("in");
                            break;
                        case RefKind.Out:
                            roles.Add("out");
                            break;
                        default:
                            roles.Add("value");
                            break;
                    }

                    roles.Add(parameter.IsWritableComponent ? "write" : "read");
                }

                var roleSummary = string.Join(",", roles);
                parts.Add($"{parameter.Name}:{parameter.TypeName}[{roleSummary}]");
            }

            var summary = string.Join("; ", parts);
            return EscapeForStringLiteral(summary);
        }

        private static string EscapeForStringLiteral(string value)
        {
            if (string.IsNullOrEmpty(value))
                return string.Empty;

            return value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"");
        }

        /// <summary>
        /// 生成 WithAll 过滤代码
        /// </summary>
        private void GenerateWithAllFilter(CodeBuilder builder, JobInfo jobInfo)
        {
            if (jobInfo.WithAllTypes.Count == 0)
                return;

            builder.AppendLine("var withAllComponents = new global::PGD.IComponents();");
            foreach (var typeSymbol in jobInfo.WithAllTypes)
            {
                var typeFullName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                builder.AppendLine($"withAllComponents.Add<{typeFullName}>();");
            }
            builder.AppendLine("query = query.WithAllComponents(withAllComponents);");
            builder.AppendLine();
        }

        /// <summary>
        /// 生成 WithAny 过滤代码
        /// </summary>
        private void GenerateWithAnyFilter(CodeBuilder builder, JobInfo jobInfo)
        {
            if (jobInfo.WithAnyTypes.Count == 0)
                return;

            builder.AppendLine("var withAnyComponents = new global::PGD.IComponents();");
            foreach (var typeSymbol in jobInfo.WithAnyTypes)
            {
                var typeFullName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                builder.AppendLine($"withAnyComponents.Add<{typeFullName}>();");
            }
            builder.AppendLine("query = query.WithAnyComponents(withAnyComponents);");
            builder.AppendLine();
        }

        /// <summary>
        /// 生成 WithNone 过滤代码
        /// </summary>
        private void GenerateWithNoneFilter(CodeBuilder builder, JobInfo jobInfo)
        {
            if (jobInfo.WithNoneTypes.Count == 0)
                return;

            builder.AppendLine("var withNoneComponents = new global::PGD.IComponents();");
            foreach (var typeSymbol in jobInfo.WithNoneTypes)
            {
                var typeFullName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                builder.AppendLine($"withNoneComponents.Add<{typeFullName}>();");
            }
            builder.AppendLine("query = query.WithoutAnyComponents(withNoneComponents);");
            builder.AppendLine();
        }
    }

    /// <summary>
    /// 语法接收器：收集所有 partial struct 候选
    /// </summary>
    internal class JobSyntaxReceiver : ISyntaxReceiver
    {
        public List<StructDeclarationSyntax> CandidateStructs { get; } = new List<StructDeclarationSyntax>();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            // 查找 partial struct 声明
            if (syntaxNode is StructDeclarationSyntax structDeclaration &&
                structDeclaration.Modifiers.Any(m => m.ValueText == "partial"))
            {
                CandidateStructs.Add(structDeclaration);
            }
        }
    }
}
